//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmJonasTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmJonasTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donald Duck
        ///Tick
        ///Trick
        ///Track
        ///Daisy Duck
        ///Dicky
        ///Dacky 
        ///Ducky
        ///Dorette Duck
        ///Dagobert Duck
        ///Dietram Duck
        ///Dussel Duck
        ///Moby Duck
        ///Primus von Quack
        ///Bolivar
        ///Dolly Duck
        ///Danny Duck
        ///Franz Gans
        ///Gustav Gans
        ///Güldo Gans
        ///Golo Gans
        ///Gisbert Gans
        ///Gitta Gans
        ///Gerry Gans
        ///Kuno Knäul
        ///Daniel Düsentrieb
        ///Zacharias Zorngiebel
        ///Quacky
        ///Hubert Bogart
        ///Nelly
        ///Habakuk
        ///Oona
        ///Striezel Streunecke
        ///Sergei Schlamassi
        ///Baptist
        ///Rita Rührig
        ///Panzerknacker
        ///Mac Moneysac
        ///Klaas Klever
        ///Gundel Gaukeley
        ///Dr. Dark
        ///Micky Maus        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Entenhausen {
            get {
                return ResourceManager.GetString("Entenhausen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bergbauern Bio-Vollmilch
        ///Bergbauern Bio-Jogurt Banane Müsli
        ///Bergbauern Bio-Jogurt Erdbeere
        ///Bergbauern Bio-Jogurt Mango Maracuja
        ///Bio-Bergbauern Jogurt Waldbeere
        ///Bio-Schaf-Frischkäse
        ///Bio-Artischocken
        ///Bio-Paranüsse
        ///Bio-Popcorn
        ///Bio-Trink-Kakao
        ///Bio-Schoko-Maulbeeren
        ///Bio-Mandel-Riegel
        ///Bio-Kokos-Chips
        ///Bio-Müsli
        ///Bio Pops
        ///Flakes Mix
        ///Bergbauern Bio-Senngold
        ///Bergbauern Bio-Senngold
        ///Bergbauern Bio-Senngold
        ///Waldquelle
        ///Club Mate
        ///fuzetea
        ///SPAR
        ///Rauch Nativa
        ///SPAR
        ///S-BUDGET
        ///SPAR
        ///Coca Cola
        ///Gasteiner        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Produkte {
            get {
                return ResourceManager.GetString("Produkte", resourceCulture);
            }
        }
    }
}
